### ISSUE TITLE
Is this library actively maintained?

### ISSUE THREAD

**Issue by orban** [datadvance/DjangoChannelsGraphqlWs#117]
The subscription story for Graphene is pretty dire, all of the other libraries haven't been updated in years and many still use the older protocol not supported by modern routers like Apollo. There are a bunch of PRs stacked to 1) support modern Django versions and 2) support the new websockets protocol. 

If the core maintainers are no longer interested in maintaining the project, would they be interested in opening up commit rights to new contributors? 

At least consider moving this to something like Jazzband. 

Thanks, and happy to help!

**Comment by pfcodes** [comment]
Bump

**Comment by daniel2751241** [comment]
Bump

**Comment by prokher** [comment]
Please take a look at the recent release. Stable 1.0 is coming...
https://github.com/datadvance/DjangoChannelsGraphqlWs/releases
