### ISSUE TITLE
Subscription not processing

### ISSUE THREAD

**Issue by dspacejs** [datadvance/DjangoChannelsGraphqlWs#12]
# Overview

When a subscription is created, it never produces a response. GraphiQL stays in the loading screen.

This is using the example code from this project and I haven't made any changes. But I did try setting the `confirm_subscriptions` option on the `GraphqlWsConsumer` to `True`, which didn't change anything (I thought it might).

# Environment

Python: `3.7.0`
django: `2.2.1`
django-channels-graphql-ws: `0.2.0`
OS: Ubuntu 18.04.2 LTS

# Steps to reproduce

1. Install dependencies

2. Run `./manage.py runserver` in the `example` directory

3. Open GraphiQL at `http://127.0.0.1:8000/`

4. Create a subscription:

```graphql
subscription {
  onChatMessageSent(chatroom: "room1", username: "testuser") {
    message
  }
}
```

No response will be given.

5. Send a chat message:

```graphql
mutation {
  sendChatMessage(chatroom: "room1", username: "testuser", message: "testing") {
    ok
  }
}
```

There will still be no response from the subscription.

The following errors are thrown in the browser console:

```
Firefox can’t establish a connection to the server at ws://127.0.0.1:8000/graphql/. 
The connection to ws://127.0.0.1:8000/graphql/ was interrupted while the page was loading.
```

**Comment by dspacejs** [comment]
Hmm, I just retried this today and it's working. I'm not aware of changing anything so I'm not sure what happened there

**Comment by japrogramer** [comment]
@dspacejs I think you had a network error ..
you can add an onError handler to your apollo
```
export const client = new ApolloClient({
  link: httpLink,
  cache,
  onError: ({ graphQLErrors, networkError, operation, forward }) => {
    if (networkError) {
      window.location.reload();
    }
  },
});

```

**Comment by dspacejs** [comment]
@japrogramer I hadn't configured Apollo yet, I was just using the GraphiQL client

**Comment by hozblok** [comment]
Hi @dspacejs ,

In the example in the `publish` method of `OnNewChatMessage` subscription there is such code:
```python
# Avoid self-notifications.
if sender == username:
    return OnNewChatMessage.SKIP

return OnNewChatMessage(chatroom=chatroom, message=message, sender=sender)
```

If you send messages as the `testuser` user and subscribe as the `testuser` user, then you do not receive notifications. In other words, being in a chat you only receive other people's messages, but not your own. So you can change `username` of the mutation to get notifications. Or you can comment out this condition to duplicate outgoing messages in your inbox.

Did my answer solve the problem?

**Comment by dspacejs** [comment]
Hey @hozblok, this was a while ago, I'm not sure what the issue was because it's working for me now. I think the problem was something different, IIRC I tried sending/receiving messages with different usernames, so the skip code shouldn't have been used.

**Comment by hozblok** [comment]
Hey @dspacejs ,
did you track messages only through the graphiql?

**Comment by prokher** [comment]
It seems the original problem is solved, so closing this.
