### ISSUE TITLE
Client default timeouts captured at import time

### ISSUE THREAD

**Issue by m-sanders** [datadvance/DjangoChannelsGraphqlWs#16]
The `GraphqlWsTransport` constant `TIMEOUT` and the `GraphqlWsTransportChannels` test client `RECEIVE_NOTHING_TIMEOUT` and `RECEIVE_NOTHING_INTERVAL` get captured at module import time as the default value. When subclassing and tweaking any of these timeout values, they are ignored. 

The workaround we're using at the moment from our test code is as follows:

```
from channels_graphql_ws.transport import GraphqlWsTransport
TIMEOUT_SECS = 0.075
GraphqlWsTransport.TIMEOUT = TIMEOUT_SECS

from channels_graphql_ws import GraphqlWsClient 

class GraphqlWsClient(BaseGraphqlWsClient):
    TIMEOUT = TIMEOUT_SECS
```

**Comment by prokher** [comment]
@m-sanders Thank you very much for reporting, we will fix this during the next sprint.

**Comment by prokher** [comment]
This is already fixed in one of recent releases.
