### ISSUE TITLE
Could you please provide an working example with django and channel2

### ISSUE THREAD

**Issue by junchiz** [datadvance/DjangoChannelsGraphqlWs#2]
I tried to use the one you provided in the readme. However, I did not make it. I am wondering if you can provide a working example in this project with django and channel 2.
Thanks a lot.

**Comment by prokher** [comment]
Indeed it is necessary. We will add this soon.

**Comment by LukeVideo** [comment]
It would be interresting to add the files to edit or create in the readme to make it easier to implement DjangoChannelsGraphqlWs.

**Comment by prokher** [comment]
Dear, @LukeVideo I am not sure I understand your previous comment. Could you please explain?

**Comment by prokher** [comment]
Example with GraphiQL browser is added in v0.2.0. Enjoy ;-)
