### ISSUE TITLE
Subscriptions are not allowed error

### ISSUE THREAD

**Issue by ahmedalttai** [datadvance/DjangoChannelsGraphqlWs#21]
Hello,
i used the messaging example but when i request:
```
subscription s{
  onChatMessageSent(chatroom: "room1", username: "testuser") {
    message
  }
}
```
the answer is:
```
{
  "errors": [
    {
      "message": "Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True"
    }
  ],
  "data": null
}
```

**Comment by IngvarListard** [comment]
As far as I can tell, GraphQL IDE is not supported in current implementation of DjangoChannelsGraphqlWs. But queries works well from code.

**Comment by prokher** [comment]
@ahmedalttai Thank you for reporting. Can you please share more details? How do you perform the request? Probably there is some kind of misconfiguration or probably you do the request through HTTP while subscriptions are essentially only possible through WebSocket. There are tests passing which somehow prove that subscriptions work, moreover we use them in our products, they work as well. So, please share the details and we will try to help.

**Comment by prokher** [comment]
@IngvarListard Thanks for observation, we have GraphiQL configured in the example, that is how we browse API currently. What GraphQL IDE are your referring, I could take a look, probably it won't take long to make it work.

**Comment by IngvarListard** [comment]
Yeah, sorry about misinformation. I messed graphiql configuration in example. I've tried it out and it works well!
The exception above appears when I try to subscribe from default [`graphene_django`](https://github.com/graphql-python/graphene-django) grpahiql endpoint.
And yes, I meant graphiql IDE. 
Thank for reply and the great well documented library!

**Comment by prokher** [comment]
@IngvarListard Thank you for warm words. 

@ahmedalttai @IngvarListard Closing this. Feel free to reopen or submit a new issue.
