### ISSUE TITLE
No matching distribution found for django-channels-graphql-ws

### ISSUE THREAD

**Issue by Nogostradamus** [datadvance/DjangoChannelsGraphqlWs#22]
pip install django-channels-graphql-ws
Output:
`Collecting django-channels-graphql-ws
  ERROR: Could not find a version that satisfies the requirement django-channels-graphql-ws (from versions: none)
ERROR: No matching distribution found for django-channels-graphql-ws
`
It's the same when I specify the exact version like 0.2.1. Do I miss something?
Python 3.6.8rc1

**Comment by prokher** [comment]
I afraid the problem is in the Python version. Code uses some Python 3.7 version. Can you try in Python 3.7?

**Comment by Nogostradamus** [comment]
Yes. It's working fine with Python 3.7.4
Thanks
