### ISSUE TITLE
Modifying subscription groups post-subscribe

### ISSUE THREAD

**Issue by qeternity** [datadvance/DjangoChannelsGraphqlWs#24]
I don't see anywhere in the docs, and going through the code it doesn't seem possible to add/remove channels groups to a subscription once the subscription has been activated. So let's say a user subscribes to groups or object pks 1 and 2 but then moments later, object pk-3 is created and we would like to subscribe users to these updates...I can't see a way to do that currently.

**Comment by prokher** [comment]
Dear @qeternity , thank you for mentioning this. I need to think a little whether it is possible in principle and if we can figure out an acceptable solution.

**Comment by prokher** [comment]
Dear @qeternity,

Indeed I could not figure out how this can be done with current architecture. Actually, only client can subscribe himself to a GraphQL subscription. Actually, it looks like the business logic you describe shall be implemented somehow manually on the business-logic level not inside GraphQL protocol handling. For example, you can create a subscription group per user and notify clients independently following you own rules. Basically this means that you will maintain client-group relationship by your own.

Moreover it looks like it is simply impossible to implement what you are talking about. In the scope of a single server (among other replicas) you simply do not know whether some particular client is connected or not. Until you keep some information about connected client in some shared storage, which is typically a database.

Probably I am missing something here, so, if you have some ideas — let's discuss.

**Comment by qeternity** [comment]
Hi @prokher - thanks for coming back to this. So the way that we have tackled this is by creating a special type of publish that includes a list of user ids that we want to target, this way we can determine at time of publish which users should receive. This allows us to work around the issue described above. It scales reasonably well but it's not perfect since all consumers must receive the full list of recipients. We had always planned to create a new user layer in channels and shard across that if scaling became a bottleneck.

I'm happy to create a PR with our code to get the conversation flowing.

**Comment by prokher** [comment]
@qeternity You and your PRs are welcome!

Since the issue seems resolved at the moment I close this ticket. If you would like to collaborate - reopen and we can continue the discussion.

Honestly, I would like to keep this package as simple as possible without adding any extra functionality/layers above. I am not sure I want to introduce extra complexity here, but if you have PR to share I would be happy to take a look.
