### ISSUE TITLE
Cannot Access to info.context.scope

### ISSUE THREAD

**Issue by caesar4321** [datadvance/DjangoChannelsGraphqlWs#27]
info.context.scope throws a wrong attribute error.

But I read

Changed
Channels scope is now stored in info.context.scope as dict. (Previously info.context was a copy of scope wrapped into the types.SimpleNamespace). The thing is the GraphQL info.context and Channels scope are different things. The info.context is a storage for a single GraphQL operation, while scope is a storage for the whole WebSocket connection. For example now use info.context.scope["user"] to get access to the Django user model.

Is there a special circumstance I can use info.context.scope?

**Comment by hozblok** [comment]
Hi @caesar4321 ,

Since then, the mechanisms have changed.
Please, try the latest version DjangoChannelsGraphqlWs (v0.4.2) and try to use `info.context` as `self.scope` of the Channels consumer, e.g `info.context.something` for `self.scope["something"]`.

Did it help?

**Comment by caesar4321** [comment]
Yes. Thank you for the explanation!

**Comment by prokher** [comment]
It seems to be resolved. Closing this. Feel free to reopen if there are issues left.
