### ISSUE TITLE
Notify same user on subscription

### ISSUE THREAD

**Issue by ckristhoff** [datadvance/DjangoChannelsGraphqlWs#29]
Hi everyone,

I'm trying to response to user on subscribe. By example, in a chatroom when an user connect to subscription, the subscription responses him with data (like a welcome message), but only to same user who just connect (no broadcast).

How can I do that? :(

**Comment by hozblok** [comment]
Hi @ckristhoff ,

Maybe you should make a special subscription for welcome messages?
When a user subscribes, let him do it in a group tied to his identifier. So the [subscribe](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/8bfab34ed6096ea8277a28bbe8603334cfec3ebc/example/example.py#L177) method will look like this:
```python
def subscribe(self, info):
    return [f"USER_GROUP_{info.context.user.pk}"]
```

Then you can use [broadcast](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/8bfab34ed6096ea8277a28bbe8603334cfec3ebc/example/example.py#L217) method of this subscription from other places with `group="USER_GROUP_{info.context.user.pk}"` to send your messages only to a specific user.

Is this option suitable for you?

**Comment by ckristhoff** [comment]
Hi @hozblok 
thanks for your answer. Creating a new group... I want to leave that option as a last resort.
What about _send_ channels method? DjangoChannelsGraphqlWs's _broadcast_ uses _group_send_ channels method but there is not a DjangoChannelsGraphqlWs method using _send_.

**Comment by ckristhoff** [comment]
Hi,
We resolve to use channels. DjangoChannelsGraphqlWs does not allows direct back messages.

**Comment by qeternity** [comment]
For future readers - we have taken to modifying the consumer so we can send to special user broadcast group, and let the consumer decide what to do. This is far preferable to send to O(n) groups which each have their own channels layer.

**Comment by prokher** [comment]
@ckristhoff, @qeternity, take a look at [this part of the example](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/example/example.py#L197). It illustrates how to skip "self-notification", i.e. how to avoid used being notified of his own messages. You can use exactly the same approach to notify only a user who sent the message! Doesn't it work for you?

**Comment by prokher** [comment]
I also responded to the question on StackOverflow: https://stackoverflow.com/a/61042400/428152

**Comment by bloodwithmilk25** [comment]
@qeternity Are you able to share that piece of code where you modifying the consumer, please? What I'm trying to do is return a list of already connected clients on new subscription right away.

**Comment by qeternity** [comment]
@prokher sorry to necropost - just seen the above. Our use case is slightly different than this, but it was the issue that closest resembled so I dropped it here.

@bloodwithmilk25 here is the code we're using...it might not be right for everyone's use case and honestly we haven't revisited since we wrote it. But basically we publish a channels message of type "broadcast.raw" which is expected to have a list of user ids attached to it. The consumers verify that a) they are subscribed to one of the relevant groups and b) that their connected user is one of the desired users. This let's us broadcast to say 1k specific users without having to make 1k broadcast calls to specific groups (i.e. user-id-as-a-group)

`
    async def broadcast_raw(self, message):
        if message["group"] not in self._sids_by_group:
            return

        # Don't publish if we're not an authorized user
        if (
            "user_ids" in message
            and str(self.scope["user"].id) not in message["user_ids"]
        ):
            return

        tasks = []
        for sid in self._sids_by_group[message["group"]]:
            tasks.append(
                self.send_json(
                    {"type": "data", "id": sid, "payload": {"data": message["payload"]}}
                )
            )
        
        await asyncio.gather(*tasks)
`

**Comment by bloodwithmilk25** [comment]
@prokher thank you so much. Will give it a try

**Comment by prokher** [comment]
@bloodwithmilk25 Feel free to reopen the issue (or post a new one) if my recipe does not work well by some reason.
