### ISSUE TITLE
Add support for apps without CHANNEL_LAYERS defined

### ISSUE THREAD

**Issue by xaralis** [datadvance/DjangoChannelsGraphqlWs#3]
In django channels 2.0+, `CHANNEL_LAYERS` is completely optional thing. However, `DjangoChannelsGraphqlWs` expects `self.channel_layer` to always be populated.

**Comment by prokher** [comment]
Indeed, we currently use [Channels Groups](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#groups) to implement subscription broadcasts. I am not sure I know a good way to implement it without groups. Do you have some particular an idea?

BTW, as far as I understand you can simply use [in-memory channel layer](https://github.com/django/asgiref) if you don't want to setup Redis:
```python
CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
```

**Comment by prokher** [comment]
It is worth mentioning that we use Channels groups to be able to send subscription notifications from other processes. So you can notify clients directly from a worker process. Of course it is only possible when Redis is used as a channel layer implementation. If you have everything running in a single process you can use in-memory channel layer as I already mentioned above.

**Comment by prokher** [comment]
I am closing this for now. @xaralis  Feel free to reopen if you have additional consideration to discuss.
