### ISSUE TITLE
Subscription is not triggered from background task

### ISSUE THREAD

**Issue by carlosalvarez91** [datadvance/DjangoChannelsGraphqlWs#36]
I am using a Celery periodic_task that triggers  a Subscription.

```
from .schema import OnUpdateOrderStatus # subscription

@periodic_task(run_every=crontab(minute='*/1'), name="completed_appointments")
def completed_appointments():

        ...

        OnUpdateOrderStatus.update_order_status(order=order, customer_id=customer.pk)

```

- [x] When I call OnUpdateOrderStatus from a Mutation or a Query on the same file it works

- [x] when I call external methods in another module from this celery periodic_task it works too,

anyone has tried to import a subscription class and call it from another module/file?

Thank you

**Comment by capaci** [comment]
Hi @carlosalvarez91 

I'm also using celery to run some background tasks. 

I hasn't studied celery deeply, but I understand that celery runs as another process, so it doesn't share the connections directly with your django application, as these two process doesn't share memory.

For this to work, you need to use some method to communicate these two process. DjangoChannelsGraphqlWs uses django-channels for the websocket management, so you can use some "channel layer", documented [here](https://channels.readthedocs.io/en/latest/topics/channel_layers.html). I'm using Redis and not having any problem with it.

**How it works**:

When you publish some subscription, django channels adds it to redis. In your main django application, there's some channels functions that listens to redis and then effectively publish the message received to all connected clients.

**Comment by capaci** [comment]
[here](https://channels.readthedocs.io/en/latest/topics/worker.html) you can view more about using channels with background process

**Comment by carlosalvarez91** [comment]
@capaci thanks for your answer,
Did you make it working?
If yes, could you post any example? The workers documentation for django channels is quite poor..

**Comment by carlosalvarez91** [comment]
@capaci thanks for your answer,

I found this example using Celery and channels
https://itnext.io/heroku-chatbot-with-celery-websockets-and-redis-340fcd160f06
tasks:
https://github.com/inoks/django-chatbot/blob/master/chat/tasks.py

I presume the graphql query/mutation would be wrapped inside the **{...}** ?

`async_to_sync(channel_layer.send)(channel_name, **{...}**)
`

if you made it working, could you provide an example? Thanks

**Comment by carlosalvarez91** [comment]
I found a solution,
so basically from a celery task you can use this client to call any query or mutation that triggers a subscription
https://github.com/datadvance/DjangoChannelsGraphqlWs#the-python-client

```
async def complete(appointment_id):
    transport = channels_graphql_ws.GraphqlWsTransportAiohttp(
        "ws://127.0.0.1:8000/graphql/"
    )
    client = channels_graphql_ws.GraphqlWsClient(transport)
    await client.connect_and_init()
    result = await client.execute(
            '''
                mutation or query 
            ''',
            variables={}
        )
    print(result["data"])
    await client.finalize()

@shared_task
def completed_appointments():
        ...
        asyncio.run( complete(appointment_id) )

```
