### ISSUE TITLE
Intergrating with Apollo.

### ISSUE THREAD

**Issue by johnpaul89** [datadvance/DjangoChannelsGraphqlWs#38]
@prokher @kingtimm  Hey, I'm trying to integrate this package with react apoolo using this  [client setup](https://www.apollographql.com/docs/react/data/subscriptions/#client-setup)

But, I can't get the subscriptions to load.
This led me to adding this other django.url.path but when I use it now query and mutation are working but subscriptions won't work.
  `django.urls.path('web', csrf_exempt(GraphQLView.as_view(graphiql=True))),`

How do I intergrate this will like this [client setup](https://www.apollographql.com/docs/react/data/subscriptions/#client-setup)

Thanks.

**Comment by raulhinojosa** [comment]
@johnpaul89 did you manage to do it?

**Comment by johnpaul89** [comment]
Yeah, I did. 😊

**Comment by raulhinojosa** [comment]
@johnpaul89 would you mind sharing how?

**Comment by johnpaul89** [comment]
You should have two urlpatterns, one for websockets and the other normal one for graphene.
 **urls.py**
`

      def graphiql(request):
           """Trivial view to serve the `graphiql.html` file."""
           del request
          # graphiql_filepath = pathlib.Path(__file__).absolute().parent / "graphiql.html"
          graphiql_filepath = os.path.join(BASE_DIR, 'Project', 'templates', 'graphiql.html')
           with open(graphiql_filepath) as f:
                return django.http.response.HttpResponse(f.read())
        
           urlpatterns = [
                path('admin/', admin.site.urls),
                path('graphql/', jwt_cookie(GraphQLView.as_view(graphiql=True))),
                path('ws/', graphiql)
       ]
`

And then on each urls for websocket and normal graphql **schema.py** should have this
`schema = graphene.Schema(query=Query, mutation=Mutation, subscription=Subscription)`

For websockets would look like this:-

`
```
class MyGraphqlWsConsumer(channels_graphql_ws.GraphqlWsConsumer):
    """Channels WebSocket consumer which provides GraphQL API."""
```

    async def on_connect(self, payload):
        """Handle WebSocket connection event."""

        # Use auxiliary Channels function `get_user` to replace an
        # instance of `channels.auth.UserLazyObject` with a native
        # Django user object (user model instance or `AnonymousUser`)
        # It is not necessary, but it helps to keep resolver code
        # simpler. Cause in both HTTP/WebSocket requests they can use
        # `info.context.user`, but not a wrapper. For example objects of
        # type Graphene Django type `DjangoObjectType` does not accept
        # `channels.auth.UserLazyObject` instances.
        # https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/23
        self.scope["user"] = await channels.auth.get_user(self.scope)

    schema = graphene.Schema(query=Query, mutation=Mutation, subscription=Subscription)
    middleware = [demo_middleware]

    
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Project.settings.dev")

application = StaticFilesWrapper(
    ProtocolTypeRouter({
        "websocket": 
        AuthMiddlewareStack(
            URLRouter([
                path('ws/', MyGraphqlWsConsumer)
            ])
        )
    })
)
```
`
And then have the normal one for graphql should look like this https://github.com/howtographql/graphql-python/blob/master/hackernews/hackernews/schema.py


This will ensure that when you create a mutation on the normal `path('graphql/', jwt_cookie(GraphQLView.as_view(graphiql=True))),` the subscription will be noticed on the websocket `path('ws/', graphiql)` 

Hope this helps.

**Comment by raulhinojosa** [comment]
@johnpaul89 thanks! but then at react side I just point regularly to /graphql with apollo? as usual? or is there something tricky on the client?

**Comment by johnpaul89** [comment]
On react you gonna use something like this as refrenced here on the apollo docs https://www.apollographql.com/docs/react/data/subscriptions/#client-setup
