### ISSUE TITLE
how do i track the users subscribed (online) to a group?

### ISSUE THREAD

**Issue by singhmitesh** [datadvance/DjangoChannelsGraphqlWs#41]
Please help.
I was using [django-channels-presence](https://django-channels-presence.readthedocs.io/en/latest/index.html)
 But the problem is i cannot get the subscription query which was sent inside the consumer and not able to get the channel_name in the subscription class. 
I need both to put create Room instance. 
Thanks in advance.

**Comment by prokher** [comment]
Dear @singhmitesh,

Sorry, I am not familiar with the software you are referring to. I could probably add the `channel_name` somehow to the context available as `info.context` (not sure it is really should be there), but query... 🤔 ... I suppose it is the responsibility of the `graphql-core` to process queries, not sure if they shall appear on the "resolvers" layer. Can you get an access to queries using regular Graphene `Query` or `Mutation` classes? I suppose no.

Probably you should join these two libraries on the [Channels routing](https://channels.readthedocs.io/en/latest/topics/routing.html?highlight=middleware#routing) level?

**Comment by singhmitesh** [comment]
Hi @prokher 

First of all thanks for replying. I am delighted:blush: 
For django-channels-presence library, `channel_name` is required and the `user` field is not mandatory. So I guess adding `channel_name` to `info.context` would be the way for people to use both the libraries together. 
Also if there is some other way to access the `channel_name`, please let me know.

As long as the query string is concerned, I was making the API to be consumed from a mobile application. And I was passing the `userToken` inside the query so that I can authenticate the user before accepting the connection. Accessing query string at the resolver level doesn't make sense :sweat_smile: But I went that way while trying your library. Anyways, in the end, I quit the idea to implement Graphql subscriptions and went with writing many raw Websocket consumers. And passed the `userToken` as a request header :sweat_smile:. 

I would definitely read your recommendations. I would try my best to work on it.
Thanks once again.

Regards
@singhmitesh

**Comment by bloodwithmilk25** [comment]
@singhmitesh Did you find a good solution?

**Comment by singhmitesh** [comment]
> @singhmitesh Did you find a good solution?
Hi @bloodwithmilk25 , 
What are you trying to achieve exactly? For me, I was having an issue accessing the query string.
i used: [django-channels-presence](https://django-channels-presence.readthedocs.io/en/latest/usage.html)
and along with that I wrote Websocket consumers and passed authToken in headers and authenticated while processing the request. Also in the Websocket consumer class, I add channel_name and user to the Room provided by the lib I mentioned. 

Do let me know what are you trying to do. I'll try my best to help you out.

**Comment by bloodwithmilk25** [comment]
@singhmitesh I have a subscription that listens to various mutations in a channel group. Somehow, I need to list all users that currently in that channel group. Also, I need to be able to all users in the group when the list of users changes.
Something like that
```subscription{
  roomOnNewChatMessage(chatroom: "test"){
    chatroom
    text
    sender
    users {
      results{
        username
      }
    }
  }
}```

**Comment by singhmitesh** [comment]
did you try the lib I mentioned [here](https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/41#issuecomment-700703193)?

**Comment by bloodwithmilk25** [comment]
@singhmitesh Yes, so now I'm passing channel name from the consumer like so:
```
class MyGraphqlWsConsumer(channels_graphql_ws.GraphqlWsConsumer):
    schema = schema

    async def on_connect(self, payload):
        """Handle WebSocket connection event."""
        await super().on_connect(payload)
        self.scope.update({'channel_name': self.channel_name})
```

My subscription looks like this
```
class OnNewChatMessage(channels_graphql_ws.Subscription):
    """Subscription triggers on a new chat message."""

    sender = graphene.String()
    chatroom = graphene.String()
    text = graphene.String()
    users = graphene.List(UserType)

    class Arguments:
        """Subscription arguments."""

        chatroom = graphene.String()

    def subscribe(self, info, chatroom=None):
        """Client subscription handler."""
        Room.objects.add(chatroom, info.context.channel_name, info.context.user)
        return [chatroom] if chatroom is not None else None

    def publish(self: dict, info, chatroom=None):
        new_msg_chatroom = self.get("chatroom")
        new_msg_text = self.get("text")
        new_msg_sender = self.get("sender")
        new_msg_users = self.get("users")

        assert chatroom is None or chatroom == new_msg_chatroom

        return OnNewChatMessage(chatroom=chatroom, text=new_msg_text,
                                sender=new_msg_sender, users=new_msg_users)

    @classmethod
    def new_chat_message(cls, chatroom, text, sender=None):
        print_debug('SUBSCRIPTION new_chat_message', color=PrintColors.WARNING)
        cls.broadcast(
            group=chatroom,
            payload={"chatroom": chatroom, "text": text, "sender": sender}
            )

    @classmethod
    def user_list_changed(cls, chatroom, users):
        print_debug('SUBSCRIPTION user_list_changed', color=PrintColors.WARNING)
        cls.broadcast(
            group=chatroom,
            payload={"chatroom": chatroom, 'users': users}
        )
```

And in signals.py I listen to `presence_changed` signal, but I'm not sure what to do in a signal itself
```
@receiver(presence_changed)
def broadcast_presence(sender, room, **kwargs):
    """
    Send updated users list to group when users list change.
    """
    OnNewChatMessage.user_list_changed(chatroom=room.channel_name,
                                       users=room.get_users())
```

**Comment by singhmitesh** [comment]
So here is the sad reality. Users or WebSocket connections can drop off anytime for what so ever reason. 
Like on subscribe() you are adding a user to the Room. You have to remove users that are no longer active. That can be handled by celery which runs a  pruning job for Rooms and Presence periodically. 
Circling back to your question. in signals you just update Rooms with the current set of users.
I think this lib does it for you. I am not sure on that.
 
PS: there is a typo in the library. I created a [PR](https://github.com/ml-learning/django-channels-presence/pull/18#issue-413467478) long back but it's not merged yet. So check that out too in case you are getting KeyError.

**Comment by bloodwithmilk25** [comment]
@singhmitesh Thanks a lot for your time, I know that, it was just a first naive try. I will then have to remove users on disconnect/unsubscribe and via celery task.
How would I send a message from a signal to trigger a subscription?

**Comment by singhmitesh** [comment]
It's totally alright. We all are just trying. That's kinda part of the problem. When someone drops off disconnect/unsubscribe is **not** called, at least when I was implementing it.

**Comment by prokher** [comment]
Dear @singhmitesh @bloodwithmilk25,

It seems you had a fruitful discussion here. Thank you for this.

@singhmitesh 

> For django-channels-presence library, channel_name is required and the user field is not mandatory. So I guess adding channel_name to info.context would be the way for people to use both the libraries together.
Also if there is some other way to access the channel_name, please let me know.

I just added `channel_name` to the context. It will be available in the ongoing update quite soon. I am not sure it is really needed, but I do not see any harm in it being there anyway.

> As long as the query string is concerned, I was making the API to be consumed from a mobile application. And I was passing the userToken inside the query so that I can authenticate the user before accepting the connection. Accessing query string at the resolver level doesn't make sense 😅 But I went that way while trying your library. Anyways, in the end, I quit the idea to implement Graphql subscriptions and went with writing many raw Websocket consumers. And passed the userToken as a request header 😅.

Raw WebSocket implementation seems reasonable to simple cases, so I fully agree and support the solution you eventually have chosen.

Meanwhile, I am closing this issue since the only `DjangoChannelsGraphqlWs` issue being reported seems to be fixed. Feel free to reopen if necessary.

Cheers.
