### ISSUE TITLE
Potential dependency conflicts between django-channels-graphql-ws and graphql-core

### ISSUE THREAD

**Issue by NeolithEra** [datadvance/DjangoChannelsGraphqlWs#42]
Hi, as shown in the following full dependency graph of **_django-channels-graphql-ws_**, **_django-channels-graphql-ws_** requires **_graphql-core >=2.0,<2.3_** ， while the installed version of  **_graphql-core (2.2.12)_** ，**_graphene 4.0.0_** requires **_graphql-core >=2.0.1_**.
According to Pip's _“first found wins”_ installation strategy, **_graphql-core 2.2.12_** is the actually installed version.
Although the first found package version **_graphql-core 2.2.12_** just satisfies the later dependency constraint **_（graphql-core >=2.0.1)_**, it will easily cause a build failure once the updated graphene introduces a higher version of **_Graphql-core_**.
According to the release history of graphene, it habitually upgrates **_Graphql-core_** in its recent releases. For instance, **_graphene 2.0.0_** upgrated **_Graphql-core_**’s constraint from **_>=1.2.dev to >=2.0.dev_**,**_graphene 2.1.3_** upgrated **_Graphql-core_**’s constraint from **_>=2.0,<3.0to >=2.1,<3.0_** and **_graphene next version_** upgrated **_Graphql-core_**’s constraint from **_>=2.1,<3.0 to >=3.1.0b1,<4._** 

### Dependency tree
```
django-channels-graphql-ws - 0.5.0
| +- aiohttp(install version:3.6.2 version range:>=3.5,<4.0)
| +- asgiref(install version:3.2.7 version range:>=3.2,<4.0)
| +- channels(install version:2.4.0 version range:>=2.2,<3.0)
| | +- asgiref(install version:3.2.7 version range:<4,>=3.2)
| | +- daphne(install version:2.5.0 version range:<3,>=2.3)
| | +- django(install version:3.0.5 version range:>=2.2)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- django(install version:3.0.5 version range:>=2.2)
| | +- asgiref (install version: version range:=3.2)
| | +- pytz(install version:2019.3 version range:*)
| | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- graphene(install version:2.1.8 version range:>=2.1,<3.0)
| | +- aniso8601(install version:7 version range:>=3,<=7)
| | +- graphql-core(install version:2.3.1 version range:<3,>=2.1)
| | | +- promise(install version:2.3 version range:>=2.3,<3)
| | | | +- six(install version:1.14.0 version range:*)
| | | | +- typing(install version:3.7.4.1 version range:>=3.6.4)
| | | +- rx(install version:1.6.1 version range:>=1.6,<2)
| | | +- six(install version:1.14.0 version range:>=1.10.0)
| | +- graphql-relay(install version:2.0.1 version range:<3,>=2)
| | | +- graphql-core(install version:2.3.1 version range:>=2.2,<3)
| | | | +- promise(install version:2.3 version range:>=2.3,<3)
| | | | +- rx(install version:1.6.1 version range:>=1.6,<2)
| | | | +- six(install version:1.14.0 version range:>=1.10.0)
| | | +- promise(install version:2.3 version range:>=2.2,<3)
| | | | +- six(install version:1.14.0 version range:*)
| | | | +- typing(install version:3.7.4.1 version range:>=3.6.4)
| | | +- six(install version:1.14.0 version range:>=1.12)
| | +- six(install version:1.14.0 version range:>=1.10.0,<2)
| +- graphql-core(install version:2.3.1 version range:>=2.2,<3.0)
| | +- promise(install version:2.3 version range:>=2.3,<3)
| | | +- six(install version:1.14.0 version range:*)
| | | +- typing(install version:3.7.4.1 version range:>=3.6.4)
| | +- rx(install version:1.6.1 version range:>=1.6,<2)
| | +- six(install version:1.14.0 version range:>=1.10.0)
| +- msgpack(install version:0.6.2 version range:>=0.6.1,<0.7.0) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Lose the version range of **_graphql-core_** to be **_>=2.0_**.
2.	Remove your direct dependency **_graphql-core_**, and use the **_graphql-core_** transitively introduced by **_graphene_**.
@prokher  Which solution do you prefer, 1 or 2 ?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by NeolithEra** [comment]
@prokher，Could you help me review this issue? Thx :p

**Comment by prokher** [comment]
@NeolithEra Thank for reporting. I am looking at this now. Well, the variant 2 seems incorrect, cause we use `graphql-core` directly, see imports in [graphql_ws_consumer.py](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/channels_graphql_ws/graphql_ws_consumer.py). Allowing dependency specification switch major version also seems improper, cause typically major version change means backward incompatible changes so such switch shall not happen without manual control and running all the tests. I am now updating dependencies and will take a look what can be done here.

**Comment by prokher** [comment]
BTW, @NeolithEra, where did you take Graphene 4.0.0 you mentioned in the original post? I see that the latest version is the beta version of 3: https://github.com/graphql-python/graphene/releases. 🤔

**Comment by prokher** [comment]
Well, eventually I do not understand the problem to solve. Current stable version of **graphene** is 2.1.8 and **django-channels-graphql-ws** seems to have completely compatible dependencies.

Setting as a target supporting all future versions of Graphene or other library this one depends on is an infeasible goal. So, please, point me the real problem to solve and I will do my best to help. Now closing this, please, reopen if needed.
