### ISSUE TITLE
Upgrade msgpack to v1.0

### ISSUE THREAD

**Issue by leandrolerena** [datadvance/DjangoChannelsGraphqlWs#44]
Upgrade msgpack dependency and use a newer Version (v1.0). At the moment, django-channels-graphql-ws is impeding me to upgrade some important dependencies. Thanks!

**Comment by prokher** [comment]
@leandrolerena, thank you for reporting. Fixed in [v0.6.0](https://github.com/datadvance/DjangoChannelsGraphqlWs/releases/tag/v0.6.0).

**Comment by prokher** [comment]
Closing, reopen if something goes wrong.

**Comment by leandrolerena** [comment]
Thank you very much!
