### ISSUE TITLE
 How to use the unsubscribe function call?

### ISSUE THREAD

**Issue by contail** [datadvance/DjangoChannelsGraphqlWs#47]
Hello,
Plz help me..

I am trying to unsubscribe, how can I call it with graphql?

I would like to know a specific example.

**Comment by prokher** [comment]
To unsubscribe, you should use the [`GQL_STOP`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_stop) message. As noted in the [`README.md`](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/README.md) `DjangoChannelsGraphqlWs` uses the same protocol as Apollo GraphQL client. The protocol is described [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#graphql-over-websocket-protocol). Please, take a look at the [`GQL_STOP` message description](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_stop).

As a JavaScript client, we use Apollo. To know more, please, take a look at the following references:
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws)
- To use Apollo, you will need a link, which can be found [here](https://github.com/apollographql/apollo-client/tree/main/src/link/ws).

Closing this, feel free to reopen.
