### ISSUE TITLE
Do you have an example when messages can be sent both ways from front end back?

### ISSUE THREAD

**Issue by sbenou** [datadvance/DjangoChannelsGraphqlWs#52]
Hi there

We have selected your library amongst the 3 recommended by the graphene website and we are using it for a project involving a machine.

I am able to create back end consumers and listen to broadcasted messages for a particular subscription but I would like to know if you have some examples of communication that are bi-directional back to front and front to back.

See the idea, is we want front end to be notified of something and front end to subscribe and receive messages. Then we need front end to acknowledge receipt of the message so we can mark it as 'delivered'. This is to make the pub/sub process fault tolerant across all apps.

I suppose that channel routers would be involved here?

Would be really great to see an example  or have some guidance ... I really want to stick to this library ... other alternatives are redis, rabbitmq or kafka but web sockets graphql subscriptions seems to be a good option since we use graphql and this library makes total sense to us.

thanks

**Comment by psdon** [comment]
bi-directional is not possible with GraphQL Subscription. You need to trigger a mutation or query instead

**Comment by sbenou** [comment]
ok thank you!
