### ISSUE TITLE
Upgrade to Channels 3

### ISSUE THREAD

**Issue by Luferov** [datadvance/DjangoChannelsGraphqlWs#58]
Hello, dear collegues.

Can you tell if you are planning to switch to channels version ^3?

**Comment by prokher** [comment]
In principal, yes, I would like to keep it up to date with latest stable versions of libraries it depends on. Is 3-rd version of Channels already here? What's new there?

**Comment by Luferov** [comment]
As a first approximation, they updated the design of the middleware. I built your library on my computer, but the tests when switching to the stable version of Django Chunnels 3.0.3 failed. I don't want to fork and change the code because I stick to the single source principle. But I really like the architecture of your library and would like to develop it.

**Comment by prokher** [comment]
Just read Channels 3 release note. The main change is about using Django's own async functions as far as I see. At first glimpse, updating doesn't seem to be difficult. If you can participate it would be great. Anyway, I will definitely pay some attention to this, but cannot promise any particular timeframe for this.

**Comment by Luferov** [comment]
No problems. Now all my time is spent on completing my Ph.D. thesis and student exams, but in February I will definitely take part in the update, if it is relevant.

**Comment by Luferov** [comment]
I generally changed the calls associated with changing the version of django 3. But there are problems, pylint tests do not pass. 
I have no idea what the problem is. 
![image](https://user-images.githubusercontent.com/26242554/104374296-bfd40100-5532-11eb-86da-8744fcedffce.png)

**Comment by prokher** [comment]
@Luferov Why did you close this? I suppose we need to support Channgels v3, so I reopen it.

**Comment by Luferov** [comment]
I changed code and it works with channels 3, but i dont know how to pass one test. I think it`s related with new configuration the asgi application (https://channels.readthedocs.io/en/stable/deploying.html). You can test it in my fork (https://github.com/devind-team/DjangoChannelsGraphqlWs). If you can help me with configuration, I start pull request. 
I updated everything to the latest state, include 2021 year.

**Comment by Luferov** [comment]
I can start pull request without one passed test, but i think its bad idea.

**Comment by prokher** [comment]
Thank you very much. I think the linter-related test failure is not a big deal, we can fix it ourselves.

**Comment by Luferov** [comment]
I started new pull request.

**Comment by MackYoel** [comment]
What about https://github.com/datadvance/DjangoChannelsGraphqlWs/pull/61 review?

**Comment by prokher** [comment]
Looks like I suddenly updated to Channels 3 in v0.8.0. Totally forgot about this MR 🤦, I am sorry. Do you still want me to review #61?

**Comment by prokher** [comment]
Anyway, Channels 3 support is (hopefully) here, so I close this issue. Feel free to reopen if there is something else to address.
