### ISSUE TITLE
Deployment to AWS API Gateway

### ISSUE THREAD

**Issue by ptrhck** [datadvance/DjangoChannelsGraphqlWs#59]
I already have graphene-django running on AWS Lambda behind API Gateway. As I have long running tasks I would like to initiate them with a query and then subscribe to it to get notified once finished. API Gateway supports websocket connections and here is a great example: [From Poll to Push: Transform APIs using Amazon API Gateway REST APIs and WebSockets](https://aws.amazon.com/de/blogs/compute/from-poll-to-push-transform-apis-using-amazon-api-gateway-rest-apis-and-websockets/)

I would like to use my current app to do that by adding subscriptions with this package. Do you have any experience deploying it to AWS Lambda + API Gateway? Or any ideas where to start?

**Comment by prokher** [comment]
@ptrhck I am sorry, I do not have such experience. Closing this since this doesn't depict an issue or a features request. It is more a question (which is perfectly fine by itself) which I cannot address.
