### ISSUE TITLE
Python 3.6 Not supported

### ISSUE THREAD

**Issue by mikejohn67** [datadvance/DjangoChannelsGraphqlWs#6]
This package does not install on pytohn3.6 dev environment..?

**Comment by hozblok** [comment]
Hi mikejohn67,

DjangoChannelsGraphqlWs uses new syntax (e.g. type annotations) and new methods (e.g. some functions from asyncio) defined since Python 3.7.
Support Python3.6 is possible, but such a task is not in the development plans for the near future.

**Comment by gotexis** [comment]
Great

When I saw from somewhere that says 3.6 is not supported, I thought like >= 3.6 not supported

Now I see >= 3.7 is supported which is ok for me :)

**Comment by prokher** [comment]
Frankly, we do not want to support Python 3.6. We love Python 3.7 and extensively use its modern features. So I am closing this as wontfix. If someone needs 3.6 support... well... we can consider PR.

**Comment by qeternity** [comment]
I've forked master and backported to 3.6 (only a few minor changes) since I wanted to test performance with PyPy (long story short, it's not a massive improvement)

https://github.com/qeternity/DjangoChannelsGraphqlWs/tree/3.6

**Comment by prokher** [comment]
Let's take a look whether we can reintegrate Python 3.6 support back to the master. @qeternity thank you for the information.

**Comment by prokher** [comment]
Eventually I added support for Python 3.6 in the v0.5.0. Feel free to test and report issues if there are any. Thanks for the issue.
