### ISSUE TITLE
Dependencies resolution conflict with channels_redis

### ISSUE THREAD

**Issue by rakyi** [datadvance/DjangoChannelsGraphqlWs#7]
channels-redis==2.3.3 depends on msgpack~=0.6.0, but django-channels-graphql-ws==0.1.16 depends on msgpack>=0.5.6,<0.6.0 and both constraints can't be satisfied at the same time. Could you, please, update the msgpack dependency?

**Comment by hozblok** [comment]
Hi, rakyi!
Dependencies updated in release [v0.1.17](https://github.com/datadvance/DjangoChannelsGraphqlWs/releases/tag/v0.1.17).

**Comment by prokher** [comment]
@rakyi Indeed, closing this. If something is wrong just reopen the issue.
