### ISSUE TITLE
Update to graphene 3

### ISSUE THREAD

**Issue by ldynia** [datadvance/DjangoChannelsGraphqlWs#70]
Hi @prokher 

I am wondering if you are gonna create a pre-release of the project to support graphene 3, and when would that be ?

Best

**Comment by W-Varg** [comment]
x2
django-graphql-jwt use graphene 3 but this package not yet, so the error skips 

django-channels-graphql-ws 0.8.0 requires graphene<3.0,>=2.1, but you have graphene 3.0b7 which is incompatible.

**Comment by prokher** [comment]
Closing this as a duplicate of #45.
