### ISSUE TITLE
Django Requirements

### ISSUE THREAD

**Issue by matclayton** [datadvance/DjangoChannelsGraphqlWs#77]
Channels 3.x works with Django 2.2+ as seen here (https://github.com/django/channels/blob/main/setup.py#L16)

However DjangoChannelsGraphqlWs requires Django >3, it would be better to align these to Django >2.2 and allow maximal flexibility. 

For example we are upgrading on Django 2.2 from Channels 1->3, which should be doable, except for the requirements in DjangoChannelsGraphqlWs (https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/pyproject.toml#L56), which I dont believe is a necessary restriction, as I can't see anything in this repro whic would need Django 3.x

**Comment by Luferov** [comment]
Also, [Django 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/) is released!

**Comment by tony** [comment]
#77 will do it.

Will make another PR for django 4.0

**Comment by Luferov** [comment]
It will be good!

**Comment by tony** [comment]
@Luferov 

PRs:
- Django 2.2: #77
- Django 4.0: #83

**Comment by prokher** [comment]
A new version 1.0.0rc is available on PyPI. It supports both the latest Django and the latest Graphene. Closing this. Feel free to reopen or file a new issue in case of problems.
