### ISSUE TITLE
GQL_STOP calls group_discard even if there are still other subscriptions on that group

### ISSUE THREAD

**Issue by wildgabu** [datadvance/DjangoChannelsGraphqlWs#8]
Relevant portion of code:

https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/20c3fa3f7bcfb1b4e42b5239fd29add75c6e5b9a/channels_graphql_ws/graphql_ws.py#L1007-L1021

If you for example create 3 subscriptions to the same subscription field, with operation ids 1, 2 and 3, you will receive (correctly) 3 GQL_DATA notifications when an event for that subscription is broadcast. 

If you then for example send a GQL_STOP for operation id 1, you should still receive GQL_DATA for operation ids 2 and 3. Instead, you receive none because unsubscribing from operation id 1 called self.channel_layer.group_discard for the same groups as the other 2 subscriptions.

Probably the correct fix would be to move:

https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/20c3fa3f7bcfb1b4e42b5239fd29add75c6e5b9a/channels_graphql_ws/graphql_ws.py#L1009

Into this if-statement:

https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/20c3fa3f7bcfb1b4e42b5239fd29add75c6e5b9a/channels_graphql_ws/graphql_ws.py#L1020-L1021

So that a group is only discarded when no operation ids are part of it anymore. And above this line:

https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/20c3fa3f7bcfb1b4e42b5239fd29add75c6e5b9a/channels_graphql_ws/graphql_ws.py#L1022

Wrap this in an `if waitlist:`, since the waitlist may now be empty if all groups you would've discarded still have operation ids attached to them.

**Comment by hozblok** [comment]
Hi wildgabu,

Thank you for your detailed research. I confirm that this looks like wrong behavior. I will let you know as soon as the fix is ready.

**Comment by hozblok** [comment]
Hi wildgabu,

You correctly pointed out the problem. In addition there is some out of sync data between threads in this place in some cases. The fix will come soon.

**Comment by wildgabu** [comment]
Great, looking forward to it!

**Comment by prokher** [comment]
Must be fixed in v0.1.18.
