### ISSUE TITLE
Django 4.0

### ISSUE THREAD

**Issue by tony** [datadvance/DjangoChannelsGraphqlWs#82]
Minimum version constraints for [4.0 release](https://docs.djangoproject.com/en/4.0/releases/4.0/)

Python >=3.8
asgiref >=3.4.1

**Comment by prokher** [comment]
The version 1.0.0rc1 is available in PyPI, it supports latest Django & Graphene, so I am closing this. Feel free to reopen or file a new issue in case of problems.
